spring.thymeleaf.cache=true
server.forward-headers-strategy=framework
app.base-url=${APP_BASE_URL:https://wc.thatcher.africa}

spring.mail.host=smtp.sendgrid.net
spring.mail.port=587
spring.mail.username=apikey
spring.mail.password=${SENDGRID_API_KEY}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.from=wcpredictor@thatcher.africa
spring.mail.reply-to=wcpredictor@thatcher.africa

logging.file.path=/app/logs
